# Generated by Django 6.0.5 on 2026-05-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='DuracionPomodoro',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='to_do',
            name='PomodorosCompletados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='to_do',
            name='PomodorosEsperados',
            field=models.IntegerField(default=1),
        ),
    ]
