# Generated by Django 6.0.5 on 2026-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_to_do_duracionpomodoro_to_do_pomodoroscompletados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do',
            name='Apuntes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
